
language: node_js

node_js:
  - '8'

before_script:
  - npm install -g gulp-cli
  - eval $(scripts/build_info.sh)
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

script:
  - test/test_cli.sh || ( touch failed; false )
  - gulp                || ( touch failed; false )
  - test ! -e failed && scripts/deploy.sh

before_install:
  - openssl aes-256-cbc -K $encrypted_2860195f5d4f_key -iv $encrypted_2860195f5d4f_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval $(ssh-agent)
  - ssh-add deploy_key
