
language: node_js

node_js:
  - '8'

before_script:
  - eval $(scripts/build_info.sh)
  - npm install -g gulp-cli
  - scripts/link.sh --copy
  - rm -f dist/js/*.min.js

script:
  - npm test || ( touch failed; false )
  - test ! -e failed && scripts/deploy.sh

before_install:
  - openssl aes-256-cbc -K $encrypted_2860195f5d4f_key -iv $encrypted_2860195f5d4f_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval $(ssh-agent)
  - ssh-add deploy_key </dev/null
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  - openssl enc -d -aes-256-cbc -a -in test/testdata.enc -out test/testdata -pass "pass:$TESTDATA"
