language: node_js
node_js:
  - "8"

before_script:
  - npm install -g gulp-cli

script:
  - ./scripts/test_cli.sh
  - gulp

# TODO: on a successful build, push the latest
#  - stable only comes from ...?
